### ISSUE TITLE
Start() method creates hundreds of threads

### ISSUE THREAD

**Issue by claudiupop** [analogdevicesinc/libsmu#102]
With libsmu-rework if you start a session with start() and read some samples, in a loop, on windows this will create hundreds of threads, while on linux this doesn't happen.

You can check this, with following code.

[example.zip](https://github.com/analogdevicesinc/libsmu/files/1161434/example.zip)

**Comment by cristi-iacob** [comment]
That branch is not available anymore. However, I tested it on the current version on Windows 10 and Ubuntu 18.04 and it seems to work properly (it doesn't create hundreds of threads). Thanks!
