### ISSUE TITLE
cannot compile on OS X

### ISSUE THREAD

**Issue by YY1205** [analogdevicesinc/libsmu#103]
ld: warning: ignoring file /usr/local/Cellar/libusb/1.0.21/lib/libusb-1.0.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/Cellar/libusb/1.0.21/lib/libusb-1.0.dylib
Undefined symbols for architecture i386:

**Comment by claudiupop** [comment]
try to use this command to install libusb 
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/cb21e9ac30e47e3ea161c4247a6397967f83c83f/Formula/libusb.rb --universal` and it should work.

**Comment by YY1205** [comment]
I used the command but still got the same error

ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libsmu.0.8.9.dylib] Error 1
make[1]: *** [src/CMakeFiles/smu.dir/all] Error 2
make: *** [all] Error 2

**Comment by claudiupop** [comment]
with the latest version of libsmu, it should work if you follow the steps from the readme file.

**Comment by commodo** [comment]
Closing since it's outdated.
There's also duplicate issue https://github.com/analogdevicesinc/libsmu/issues/105
