### ISSUE TITLE
Cannot compile on OS X

### ISSUE THREAD

**Issue by cradhakrish** [analogdevicesinc/libsmu#105]
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libsmu.0.8.9.dylib] Error 1
make[1]: *** [src/CMakeFiles/smu.dir/all] Error 2
make: *** [all] Error 2

**Comment by claudiupop** [comment]
install libusb with this command and it should work 
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/cb21e9ac30e47e3ea161c4247a6397967f83c83f/Formula/libusb.rb --universal`

**Comment by cradhakrish** [comment]
Thanks! that did the first step. Could you please help with this:

/Users/uofiece/libsmu/bindings/python/src/pysmu.cpp:27:10: fatal error: 
      'cstdint' file not found
#include <cstdint>
         ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
make[2]: *** [bindings/python/timestamp] Error 1
make[1]: *** [bindings/python/CMakeFiles/python.dir/all] Error 2
make: *** [all] Error 2

**Comment by claudiupop** [comment]
please take a look at https://github.com/analogdevicesinc/libsmu/issues/76 and see if that can help.

**Comment by sfeng15** [comment]
Hi, I have encountered and issue when typing ''sudo make install''. The error message is attached. Thanks.
<img width="650" alt="screen shot 2017-09-06 at 6 22 23 pm" src="https://user-images.githubusercontent.com/11356348/30138928-81d3d5c8-9330-11e7-9bde-b4887cbcddff.png">

**Comment by cradhakrish** [comment]
I tried this but got the same error. Will the version of Python matter? I am doing this on 2.7.13. When I used another machine with 2.7.12 the process went through fine.

**Comment by claudiupop** [comment]
sfeng15: when you do cmake try something like `cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ ..` and then `sudo make install`

**Comment by claudiupop** [comment]
cradhakrish: I can't tell you if the version of python matter. Did you installed python via homebrew ?

**Comment by cradhakrish** [comment]
Yes I installed python using homebrew and it installs version 2.7.13. Is there way to install 2.7.12 using homebrew

**Comment by cradhakrish** [comment]
I noticed that cmake finds python at the location below:
-- Detecting C compile features - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libusb-1.0'
--   Found libusb-1.0, version 1.0.21
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.10") 
-- Looking for getopt


is this correct - I tried to link to the version installed by homebrew but I still get the same path.

**Comment by claudiupop** [comment]
It is ok to find the same path. I tried to install it and i don't get that error. Could you tell me what clang version do you have? ( `clang --version` )  I have "Apple LLVM version 7.0.2 (clang-700.1.81)"  running on OS X 10.10.5. What steps did you make to get that error ?

**Comment by YY1205** [comment]
I got the same error. This is my version:

clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by cradhakrish** [comment]
I was able to build libsmu. I get the following warnings:

warning: no files found matching '*.[ch]' under directory 'src'
warning: no previously-included files matching 'CMakeLists.txt' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
writing manifest file 'pysmu.egg-info/SOURCES.txt'

Is that okay? 

Also, I had to set 

-DCMAKE_INSTALL_PREFIX=/usr/local/

**Comment by dNechita** [comment]
Hi,

We will look into as soon as Claudiu returns from vacation, which is next week.

**Comment by claudiupop** [comment]
@cradhakrish Those warning shouldn't be a problem.  What steps have you done to get past that error ?

**Comment by commodo** [comment]
Closing since outdated.
If it's still an issue, feel free to re-open.
