### ISSUE TITLE
Hot Plug question

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/libsmu#120]
I've been trying to figure out how the hotplug attach and detach functions are supposed to work in Python.

I've modified the example hotplug.py file to add steps like I'm using in my main program.
It seems that hotplug does not work if session is started (running). In the attached file it seems to work if you comment out the session.start(0) in line 47 but with that line included the program terminates after a few seconds after the board is unplugged.

[hotplug.zip](https://github.com/analogdevicesinc/libsmu/files/2385833/hotplug.zip)

Thanks for any guidance on this.

Doug

**Comment by cristi-iacob** [comment]
We have modified the hotplug mechanism. It will be available in the next libsmu version (which will be available as soon as possible). Also, we have modified the hotplug examples. 
Thanks!
