### ISSUE TITLE
macos installation instructions issue

### ISSUE THREAD

**Issue by saraheno** [analogdevicesinc/libsmu#167]
Hi Alexandra, Doug,
We are now having another problem with our MacOS boards.  A student was running the dc-meter.sh last week successfully on Cataline MacOS.  He was playing with the ADALM1000 between the labs, and now the program hangs.  It does open up, but he cannot change any of the settings, etc.  We noticed there were fixes for hanging with macos in the latest release and so wanted to install it and see if this fixed his issue.  We went to https://github.com/analogdevicesinc/libsmu/blob/master/README.md  to follow the MacOS instructions.  However, one of the listed commands does not work.  brew install python3 python3-setuptools python3-pip

 I attach a screen grab with the error
Any help would be appreciated. 

<img width="573" alt="Screen Shot 2020-09-21 at 10 29 57 AM" src="https://user-images.githubusercontent.com/5215288/93781957-f8547580-fbf7-11ea-89f4-21d330217d09.png">

**Comment by AlexandraTrifan** [comment]
Please try to run:
`brew install python3`
`pip3 install --upgrade pip`
`pip3 install setuptools`
`pip3 install cython`

-Alexandra

**Comment by saraheno** [comment]
Hi Alexandra.  I notice that the official instructions in the Readme still have the old command.  would it make sense to change that to these?

**Comment by AlexandraTrifan** [comment]
Hi,

I updated the documentation to only install "python3" package.

-Alexandra

**Comment by AlexandraTrifan** [comment]
Closing this. Can be reopened if there are any other issues.
