### ISSUE TITLE
Pysmu Module Not Found Error in Anaconda Python, Ubuntu 20.04

### ISSUE THREAD

**Issue by samuelburnham** [analogdevicesinc/libsmu#168]
I am able to install the .deb files and run Pysmu examples in Ubuntu 20.04 with no issues. However, when running with the latest Anaconda I get a ModuleNotFoundError when attempting to import the pysmu library. I have tried the Linux FAQ methods and building from source, at which point I get another module error for setuptools although it is installed in my Anaconda environment. Any ideas on why this might be?

Also, for development purposes it would be great to support virtual environments out of the box. Are there any plans to deploy pysmu to PyPI or the Anaconda Cloud?

**Comment by tfcollins** [comment]
Conda packages get put in a different place than standard pip or manually installed packages if not in the conda environment. This is how they stay isolated and likely the reason you cannot import pysmu.

If you are curious there are some conda packages being staged that are known to work on Linux https://wiki.analog.com/university/tools/conda .
