### ISSUE TITLE
Installing libsmu .deb package on Ubuntu 18.04 (additional commands required)

### ISSUE THREAD

**Issue by StefanMack** [analogdevicesinc/libsmu#170]
I installed the Debian package "libsmu-1.0.3-ubuntu-18.04-amd64.deb" on some lab machines and then installed "python3-pysmu_1.0.3-1-ubuntu-18.04-amd64.deb" there. In the end I tested this installation by loading the module "pysmu".
The following error occurred on all computers when calling `import pysmu` under Python 3.69:

```
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysmu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pysmu/__init__.py", line 6, in <module>
    from .libsmu import *
ImportError: libsmu.so.1: cannot open shared object file: No such file or directory
```
It turned out that the following two Linux commands were missing in the previous installations:

```
sudo usermod -a -G plugdev <username>
sudo ldconfig
```
Only after entering these two commands "pysmu" could be imported without error message.
Maybe these commands are missing in the above mentioned Debian packages.

**Comment by AlexandraTrifan** [comment]
Hi,

Thank you for the update. 
"sudo ldconfig" is already added in the README page for libsmu.
We will also check the other command and update the README page as needed.

Thank you!
-Alexandra
