### ISSUE TITLE
Revision F hardware details?

### ISSUE THREAD

**Issue by greyltc** [analogdevicesinc/libsmu#180]
I see a few new features in the library here that depend on revision F of the hardware. Notably there seem to have been some changes to the signals  available on the headers. I can't seem to find any details on this new revision (a schematic). Do you know where I could find this?

**Comment by msuciu** [comment]
You can find here the latest schematic for rev F. https://wiki.analog.com/university/tools/m1k/hw?rev=1613991623#revision_f

**Comment by greyltc** [comment]
Thank you!
