### ISSUE TITLE
Make error, no module named setuptools

### ISSUE THREAD

**Issue by SuperSecureHuman** [analogdevicesinc/libsmu#194]
I am trying to install, but it says module error. I can confirm that I have installed setuptools.

![image](https://user-images.githubusercontent.com/88489071/148163802-3b8e62a7-0bba-4511-bf7d-1a6bce370ed7.png)

System info

![image](https://user-images.githubusercontent.com/88489071/148163838-d236163c-ee39-4645-a96c-4323347cd088.png)

Thanks!

**Comment by AlexandraTrifan** [comment]
Hi,

Can you send us the output log from the CMake step? This way we can check if cmake linked to the correct python version, the one in miniconda/envs/python37.

-Alexandra

**Comment by SuperSecureHuman** [comment]
[CMakeOutput.log](https://github.com/analogdevicesinc/libsmu/files/7813007/CMakeOutput.log)

Here is the log file

I am not exactly sure about cmake being linked. Can you link an article or something?

Thanks!

**Comment by AlexandraTrifan** [comment]
Please also attach the CMakeCache.txt and a printscreen from the command line, from when you ran the step "cmake ..", right before "make".
When "cmake .." is called, the project searches for some dependent libraries. Python is one of those dependencies, and CMake will find the one that's in the system Path. 

-Alexandra

**Comment by SuperSecureHuman** [comment]
cmake .. 

![image](https://user-images.githubusercontent.com/88489071/148186667-c12f6920-9dd7-49c0-a051-2279985dc496.pn


Cmake Cache
[CMakeCache.txt](https://github.com/analogdevicesinc/libsmu/files/7813324/CMakeCache.txt)
g)


Here you go

**Comment by AlexandraTrifan** [comment]
Hi,

The problem is that CMake detects python2.7 before python3 and uses that one. Please remove everything from your "build" directory and try to build it again in the following way: 

> cmake -DUSE_PYTHON2=OFF ..
make

-Alexandra

**Comment by SuperSecureHuman** [comment]
Yep!
It did the trick!

Thanks
You might wanna update readme (the table where you put flags)

I'll close this issue now :)

**Comment by AlexandraTrifan** [comment]
We are working on some updates and this flag will disappear in the future.

-Alexandra
