### ISSUE TITLE
check return codes for all relevant libusb function calls

### ISSUE THREAD

**Issue by radhermit** [analogdevicesinc/libsmu#29]
We should really be handling potential error cases when using usb functionality. Otherwise, cases such as yanking the usb cable at the wrong time can cause unhandled LIBUSB_ERROR_NO_DEVICE errors and other similar situations.

**Comment by itdaniher** [comment]
This has been the case since sometime before de2edb3adae0d6f0311853abbf80a93c1bd7b385.
