### ISSUE TITLE
invalid device serial number

### ISSUE THREAD

**Issue by dansteingart** [analogdevicesinc/libsmu#50]
On ubuntu 15.04 and 14.04. as well as OS X 10.10, I get this error upon running pysmu.py:

```
Using libusb hotplug
device insert 0xb40330
Traceback (most recent call last):
  File "pysmu.py", line 143, in <module>
    A.set_mode('v')
  File "pysmu.py", line 84, in set_mode
    libpysmu.set_mode(self.dev, self.chan, 1)
ValueError: invalid device serial number
```

thanks in advance

**Comment by dansteingart** [comment]
unplugging and plugging 3 times back in worked.... anything deterministic that can be done here?

**Comment by dansteingart** [comment]
after a while it defaults back to this error.  any insight would be much appreciated

**Comment by dansteingart** [comment]
if it helps, when it fails I get this error:  

![screen shot 2015-09-10 at 8 19 19 pm](https://cloud.githubusercontent.com/assets/152047/9804238/9afc7722-57f9-11e5-93ee-9a17f7d6c8e0.png)

**Comment by radhermit** [comment]
Sorry for responding so slowly, does this still occur for you using the latest code in master? I'm unable to reproduce it.

**Comment by cristi-iacob** [comment]
We have modified the hotplug mechanism. It will be available in the next version. It should solve this problem. Thanks!
