### ISSUE TITLE
expose calibration support 

### ISSUE THREAD

**Issue by radhermit** [analogdevicesinc/libsmu#59]
Once the firmware changes are done, add calibration support in libsmu and in the python bindings.

**Comment by acozma** [comment]
Calibration support was added in libsmu v0.88 and in firmware v2.06

**Comment by radhermit** [comment]
Support added to the smu binary to display/reset/set calibration as well as the python bindings. Some minor bugs might remain in the example python script, but they can be handled elsewhere.
