### ISSUE TITLE
Questions on cal

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/libsmu#62]
Someone asked by email:
------------------------------------------
I have loaded the latest firmware which should support calibration read and write onto an m1k.

I have installed libsmu-setup-x86 and pysmu-0.88.win32-py2.7 from AppVeyor on my Windows 8 computer.

I have edited one of my simpler Python programs to import the new pysmu rather than the previous libpysmu. This seems to work for all the previous functions but it returns an error when I try to read back the calibration data using print(dev.calibration) as in your example on GitHub. 

Does the board have to be calibrated ( ie write_calibration ) before this will work? The same thing happens when I run the calibration example script without a file name where it falls through and does the print(dev.calibration). Is there something else that needs to be loaded?

I have another question. How does someone un-do the calibration for example if there were to be a typo when entering the file or a miss-measurment?
Do you just write new setting with no difference in the numbers ( ie. 
0.0000, 0.0000
2.5000, 2.5000 .... ) or is there a way to just wipe the settings? 
Does reloading the firmware wipe the calibration settings?
-------------------------------

Thanks

**Comment by radhermit** [comment]
I think uncalibrated or unsupported boards should now return the default calibration settings for print(dev.calibration) or at least that's how it works now for me. I think I made a commit recently regarding calibration resetting which probably fixed that.

To undo calibration, just run the calibration script or the smu binary with the -r argument. I added support to both to reset device calibration.

There's also updated info about resetting calibration at https://wiki.analog.com/university/tools/m1k/calibration.
