### ISSUE TITLE
switch to upstream libusb for windows once hotplugging support is merged

### ISSUE THREAD

**Issue by radhermit** [analogdevicesinc/libsmu#96]
Currently upstream appears to be targeting 1.0.22 (the next release) for merging windows hotplug support.

**Comment by radhermit** [comment]
See https://github.com/libusb/libusb/issues/86 for tracking upstream status.

**Comment by radhermit** [comment]
Just to update, looks like the windows hotplug merge was bumped to 1.0.23 as 1.0.22 is nearing release with a couple RCs out already.

**Comment by AlexandraTrifan** [comment]
We are no longer using the hotplug branch in libsmu. This was never merged back into the master libusb. We are now using the latest version of libusb.
Closing this.
