### ISSUE TITLE
reads in non-continuous mode seem unstable

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/libsmu#99]
The libsmu from the rework branch seems to have stability issues.
Data capture works for a while (couple of seconds, maybe more) and then it stops retrieving any data.
The 'read' and 'read-write' examples can be used to easily reproduce the issue. When ran, they display captured data for a couple of seconds then they freeze on the last captured data.
I'm experiencing this on a linux virtual machine.
In continuous mode everything works well.

The libsmu version I've used:  https://github.com/analogdevicesinc/libsmu/commit/5cf7ec8c2f76c6467847a6c4bf5a7d133021d9f9

**Comment by cristi-iacob** [comment]
That branch is not available anymore. I couldn't reproduce the bug on the last available version.
